"""add_inspection_evidence_metadata

Revision ID: 2cc42e07c38d
Revises: 7defed6cdd6d
Create Date: 2026-09-11 12:27:50.255527
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '2cc42e07c38d'
down_revision: Union[str, Sequence[str], None] = '7defed6cdd6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inspections', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('inspections', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('inspections', sa.Column('location_accuracy_m', sa.Float(), nullable=True))
    op.add_column('inspections', sa.Column('location_captured_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('inspections', sa.Column('location_source', sa.String(length=30), nullable=True))
    op.add_column('inspections', sa.Column('scan_started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('inspections', sa.Column('scan_completed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inspections', 'scan_completed_at')
    op.drop_column('inspections', 'scan_started_at')
    op.drop_column('inspections', 'location_source')
    op.drop_column('inspections', 'location_captured_at')
    op.drop_column('inspections', 'location_accuracy_m')
    op.drop_column('inspections', 'longitude')
    op.drop_column('inspections', 'latitude')
    # ### end Alembic commands ###
