"""create_escalations_table

Revision ID: c2553b8e24fe
Revises: 2cc42e07c38d
Create Date: 2026-09-11 20:17:36.909857
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'c2553b8e24fe'
down_revision: Union[str, Sequence[str], None] = '2cc42e07c38d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('escalations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('trigger_inspection_id', sa.Integer(), nullable=False),
    sa.Column('failed_inspection_count', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trigger_inspection_id'], ['inspections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_escalations_level'), 'escalations', ['level'], unique=False)
    op.create_index(op.f('ix_escalations_product_id'), 'escalations', ['product_id'], unique=False)
    op.create_index(op.f('ix_escalations_status'), 'escalations', ['status'], unique=False)
    op.create_index(op.f('ix_escalations_trigger_inspection_id'), 'escalations', ['trigger_inspection_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_escalations_trigger_inspection_id'), table_name='escalations')
    op.drop_index(op.f('ix_escalations_status'), table_name='escalations')
    op.drop_index(op.f('ix_escalations_product_id'), table_name='escalations')
    op.drop_index(op.f('ix_escalations_level'), table_name='escalations')
    op.drop_table('escalations')
    # ### end Alembic commands ###
