import {
  InspectionRecord,
  CodifiedRule,
  Section36Notice,
  ComplianceCertificate,
  RepeatOffender,
} from './types';

export const SAMPLE_RULES: CodifiedRule[] = [
  {
    id: 1,
    ruleCode: 'LG-MFR',
    ruleNumber: 'Rule 4 & 6(1)(a)',
    title: 'Manufacturer, Packer or Importer Name & Address',
    requirement: 'Full name, complete postal address with PIN and state must be clearly declared.',
    severity: 'critical',
    version: 2,
    effectiveFrom: '2011-04-01',
    status: 'active',
    jurisdiction: 'India (Central)',
    checksCount: 3,
  },
  {
    id: 2,
    ruleCode: 'LG-COMMODITY',
    ruleNumber: 'Rule 6(1)(b)',
    title: 'Generic or Common Commodity Name',
    requirement: 'Generic name of product in prominent lettering on principal display panel.',
    severity: 'major',
    version: 1,
    effectiveFrom: '2011-04-01',
    status: 'active',
    jurisdiction: 'India (Central)',
    checksCount: 2,
  },
  {
    id: 3,
    ruleCode: 'LG-QTY',
    ruleNumber: 'Rule 5 & Schedule II',
    title: 'Net Quantity Metric Standard Declaration',
    requirement: 'Standard SI metric units (g, kg, ml, l) with correct abbreviation spacing.',
    severity: 'critical',
    version: 2,
    effectiveFrom: '2011-04-01',
    status: 'active',
    jurisdiction: 'India (Central)',
    checksCount: 4,
  },
  {
    id: 4,
    ruleCode: 'LG-MRP',
    ruleNumber: 'Rule 6(1)(e)',
    title: 'Maximum Retail Price (MRP) & Unit Sale Price',
    requirement: 'MRP inclusive of all taxes, plus unit sale price (USP) for commodities > 1kg/1L.',
    severity: 'critical',
    version: 3,
    effectiveFrom: '2022-01-01',
    status: 'active',
    jurisdiction: 'India (Central)',
    checksCount: 5,
  },
  {
    id: 5,
    ruleCode: 'LG-DATE',
    ruleNumber: 'Rule 6(1)(d)',
    title: 'Month & Year of Manufacture or Packaging',
    requirement: 'Clear MM/YYYY or Month Year notation without misleading forward dating.',
    severity: 'critical',
    version: 1,
    effectiveFrom: '2011-04-01',
    status: 'active',
    jurisdiction: 'India (Central)',
    checksCount: 2,
  },
  {
    id: 6,
    ruleCode: 'LG-BBE',
    ruleNumber: 'Rule 6(1)(d) & FSSAI Alignment',
    title: 'Best Before / Expiry for Perishable Commodities',
    requirement: 'Mandatory shelf-life expiry timeline for food, cosmetics, and drugs.',
    severity: 'major',
    version: 2,
    effectiveFrom: '2017-06-23',
    status: 'active',
    jurisdiction: 'India (Central)',
    checksCount: 2,
  },
  {
    id: 7,
    ruleCode: 'LG-CARE',
    ruleNumber: 'Rule 6(5)',
    title: 'Consumer Care Contact Details',
    requirement: 'Name, address, telephone number and email address of grievance officer.',
    severity: 'major',
    version: 2,
    effectiveFrom: '2021-12-01',
    status: 'active',
    jurisdiction: 'India (Central)',
    checksCount: 3,
  },
  {
    id: 8,
    ruleCode: 'LG-COO',
    ruleNumber: 'Rule 6(10) & Rule 11',
    title: 'Country of Origin for Imported Commodities',
    requirement: 'Country of manufacture or assembly explicitly declared on imported goods.',
    severity: 'major',
    version: 2,
    effectiveFrom: '2017-06-23',
    status: 'active',
    jurisdiction: 'India (Central)',
    checksCount: 2,
  },
  {
    id: 9,
    ruleCode: 'LG-LEGIBILITY',
    ruleNumber: 'Rule 9(6) & Table I',
    title: 'Minimum Font Height & Visual Prominence',
    requirement: 'Minimum numeral and uppercase letter height (1.0mm - 4.0mm based on packaging area).',
    severity: 'major',
    version: 1,
    effectiveFrom: '2011-04-01',
    status: 'active',
    jurisdiction: 'India (Central)',
    checksCount: 3,
  },
];

export const SAMPLE_INSPECTIONS: InspectionRecord[] = [
  {
    id: 'INSP-2026-001',
    productName: 'NutriRich Digestive Biscuits',
    brand: 'NutriRich Foods',
    sku: 'NR-DIG-500G',
    category: 'Packaged Food & Confectionery',
    barcode: '8901030829143',
    declaredMrp: 145.0,
    netQuantity: '500 g',
    mfgMonthYear: '08/2026',
    storeName: 'Reliance Smart Superstore, Sector 18',
    location: 'Noida, Gautam Buddha Nagar, Uttar Pradesh',
    gpsCoords: { lat: 28.5708, lng: 77.3261 },
    status: 'COMPLIANT',
    complianceScore: 100,
    createdAt: '2026-09-09T14:30:00Z',
    imageUrl: 'https://images.unsplash.com/photo-1590080875515-8a3a8dc5735e?auto=format&fit=crop&w=800&q=80',
    tamperDetected: false,
    scanSource: 'vendor_self_audit',
    declarations: [
      {
        fieldName: 'mrp',
        label: 'Maximum Retail Price',
        value: '₹ 145.00 (incl. of all taxes)',
        rawValue: 'MRP Rs 145.00 INCL OF ALL TAXES (USP Rs 0.29/g)',
        confidence: 98.4,
        status: 'extracted',
        ruleCode: 'LG-MRP',
        bbox: { ymin: 22, xmin: 58, ymax: 34, xmax: 92, label: 'MRP & USP', status: 'pass', field_name: 'mrp' },
      },
      {
        fieldName: 'net_quantity',
        label: 'Net Quantity',
        value: '500 g',
        rawValue: 'Net Qty: 500g',
        confidence: 99.1,
        status: 'extracted',
        ruleCode: 'LG-QTY',
        bbox: { ymin: 36, xmin: 58, ymax: 45, xmax: 85, label: 'Net Qty', status: 'pass', field_name: 'net_quantity' },
      },
      {
        fieldName: 'manufacturing_date',
        label: 'Mfg Month & Year',
        value: '08/2026',
        rawValue: 'MFD. 08/2026 - USE BY 02/2027',
        confidence: 96.7,
        status: 'extracted',
        ruleCode: 'LG-DATE',
        bbox: { ymin: 47, xmin: 58, ymax: 56, xmax: 94, label: 'Mfg Date', status: 'pass', field_name: 'manufacturing_date' },
      },
      {
        fieldName: 'manufacturer',
        label: 'Manufacturer Details',
        value: 'NutriRich Foods Pvt Ltd, Plot 42, Ecotech III, Greater Noida 201306, UP, India',
        rawValue: 'Mfd by: NutriRich Foods Pvt Ltd, Plot 42, Ecotech III, Greater Noida 201306',
        confidence: 97.2,
        status: 'extracted',
        ruleCode: 'LG-MFR',
        bbox: { ymin: 58, xmin: 10, ymax: 76, xmax: 92, label: 'Manufacturer Name & Address', status: 'pass', field_name: 'manufacturer' },
      },
      {
        fieldName: 'consumer_care',
        label: 'Consumer Care Contact',
        value: 'Tel: 1800-200-9944, Email: care@nutririchfoods.in',
        rawValue: 'Consumer Care: 1800-200-9944 / care@nutririchfoods.in',
        confidence: 95.8,
        status: 'extracted',
        ruleCode: 'LG-CARE',
        bbox: { ymin: 78, xmin: 10, ymax: 92, xmax: 92, label: 'Consumer Care Cell', status: 'pass', field_name: 'consumer_care' },
      },
    ],
    violations: [],
  },
  {
    id: 'INSP-2026-002',
    productName: 'GlowHerb Ayurvedic Hair Oil',
    brand: 'GlowHerb Natural Care',
    sku: 'GH-AHO-100ML',
    category: 'Cosmetics & Personal Care',
    barcode: '8904012891045',
    declaredMrp: 180.0,
    netQuantity: '100 ml',
    mfgMonthYear: '07/2026',
    storeName: 'Arogya Medical & General Store',
    location: 'Connaught Place, Central Delhi, Delhi',
    gpsCoords: { lat: 28.6315, lng: 77.2167 },
    status: 'NON_COMPLIANT',
    complianceScore: 68,
    createdAt: '2026-09-08T11:15:00Z',
    imageUrl: 'https://images.unsplash.com/photo-1608248597359-007e050044fa?auto=format&fit=crop&w=800&q=80',
    tamperDetected: false,
    scanSource: 'field_inspector',
    declarations: [
      {
        fieldName: 'mrp',
        label: 'Maximum Retail Price',
        value: '₹ 180.00',
        rawValue: 'MRP Rs 180.00 INCL TAX',
        confidence: 94.2,
        status: 'extracted',
        ruleCode: 'LG-MRP',
        bbox: { ymin: 24, xmin: 50, ymax: 33, xmax: 88, label: 'MRP', status: 'pass', field_name: 'mrp' },
      },
      {
        fieldName: 'net_quantity',
        label: 'Net Quantity',
        value: '100 ml',
        rawValue: '100ml',
        confidence: 96.0,
        status: 'extracted',
        ruleCode: 'LG-QTY',
        bbox: { ymin: 35, xmin: 50, ymax: 42, xmax: 75, label: 'Net Qty', status: 'pass', field_name: 'net_quantity' },
      },
      {
        fieldName: 'font_legibility',
        label: 'Numeral & Letter Height',
        value: '0.72 mm',
        rawValue: 'Measured: 0.72mm physical height (Table I threshold: 1.0mm for pkg area 120cm²)',
        confidence: 91.5,
        status: 'review',
        ruleCode: 'LG-LEGIBILITY',
        bbox: { ymin: 44, xmin: 48, ymax: 56, xmax: 94, label: 'Font Height Defect (0.72mm < 1.0mm)', status: 'fail', field_name: 'font_legibility' },
      },
    ],
    violations: [
      {
        id: 'VIOL-002-1',
        ruleCode: 'LG-LEGIBILITY',
        ruleTitle: 'Rule 9(6) — Sub-Standard Declaration Font Height',
        legalCitation: 'Legal Metrology (Packaged Commodities) Rules 2011, Rule 9(6) Table I',
        fieldName: 'font_legibility',
        severity: 'major',
        status: 'open',
        message: 'The numeral height of net quantity and MRP is 0.72mm, which is below the mandatory minimum height of 1.0mm for packages with display area between 50cm² and 100cm².',
        detectedValue: '0.72 mm',
        expectedValue: '≥ 1.0 mm',
        confidence: 91.5,
        fixSuggestion: 'Increase net quantity and price text height on the primary artwork to at least 1.2mm to guarantee legal compliance across print runs.',
        bbox: { ymin: 44, xmin: 48, ymax: 56, xmax: 94, label: 'Font Height Violation', status: 'fail', field_name: 'font_legibility' },
      },
    ],
  },
  {
    id: 'INSP-2026-003',
    productName: 'CrispWave Kettle Cooked Chips',
    brand: 'CrispWave Snacks Ltd',
    sku: 'CW-KC-75G',
    category: 'Snacks & Savouries',
    barcode: '8906001229041',
    declaredMrp: 50.0,
    netQuantity: '75 g',
    mfgMonthYear: '06/2026',
    storeName: 'Kalyan Provision Stores, Railway Station Road',
    location: 'Kanpur, Uttar Pradesh',
    gpsCoords: { lat: 26.4499, lng: 80.3319 },
    status: 'NON_COMPLIANT',
    complianceScore: 42,
    createdAt: '2026-09-09T09:40:00Z',
    imageUrl: 'https://images.unsplash.com/photo-1566478989037-eec170784d0b?auto=format&fit=crop&w=800&q=80',
    tamperDetected: true,
    tamperReason: 'Overlaid adhesive sticker detected over original printed MRP. Underneath MRP: ₹35.00, Sticker MRP: ₹50.00.',
    noticeStatus: 'draft',
    noticeId: 'NOT-2026-0089',
    scanSource: 'field_inspector',
    declarations: [
      {
        fieldName: 'mrp',
        label: 'Maximum Retail Price',
        value: '₹ 50.00 (Tampered Sticker)',
        rawValue: 'STICKER: Rs 50/- | ORIGINAL UNDERNEATH: Rs 35/-',
        confidence: 97.8,
        status: 'review',
        ruleCode: 'LG-MRP',
        bbox: { ymin: 20, xmin: 52, ymax: 38, xmax: 95, label: 'Dual-MRP Sticker Seam Detected', status: 'fail', field_name: 'mrp' },
      },
      {
        fieldName: 'consumer_care',
        label: 'Consumer Care Contact',
        value: 'MISSING',
        rawValue: null,
        confidence: 99.0,
        status: 'not_found',
        ruleCode: 'LG-CARE',
      },
    ],
    violations: [
      {
        id: 'VIOL-003-1',
        ruleCode: 'LG-MRP',
        ruleTitle: 'Rule 6(1)(e) & Section 36 — Dual Pricing / Altered Price Sticker',
        legalCitation: 'Legal Metrology Act 2009 Sec 36(1) & LM(PC) Rules 2011 Rule 18(2)',
        fieldName: 'mrp',
        severity: 'critical',
        status: 'open',
        message: 'Illegal secondary sticker of ₹50.00 pasted over original manufacturer declared price of ₹35.00. Prohibited under Rule 18(2).',
        detectedValue: '₹ 50.00 (Overlaid Sticker on ₹ 35.00)',
        expectedValue: 'Single inviolable declared price',
        confidence: 97.8,
        fixSuggestion: 'Immediately recall tampered stock. Retailers and packers are strictly prohibited from sticking revised prices without Gazette notification.',
        bbox: { ymin: 20, xmin: 52, ymax: 38, xmax: 95, label: 'Sticker Anomaly', status: 'fail', field_name: 'mrp' },
      },
      {
        id: 'VIOL-003-2',
        ruleCode: 'LG-CARE',
        ruleTitle: 'Rule 6(5) — Missing Mandatory Consumer Grievance Contact',
        legalCitation: 'LM(PC) Amendment Rules 2021, Rule 6(5)',
        fieldName: 'consumer_care',
        severity: 'major',
        status: 'open',
        message: 'No designated email address or toll-free helpline number found for consumer complaints.',
        detectedValue: 'Not Found',
        expectedValue: 'Valid Phone + Email Address',
        confidence: 99.0,
        fixSuggestion: 'Print dedicated consumer care officer name, phone number, and official email on back panel.',
      },
    ],
  },
  {
    id: 'INSP-2026-004',
    productName: 'FreshMeadow Farm Honey',
    brand: 'FreshMeadow Naturals',
    sku: 'FM-HNY-250G',
    category: 'Natural & Organic Foods',
    barcode: '8907819200412',
    declaredMrp: 210.0,
    netQuantity: '250 g',
    mfgMonthYear: '05/2026',
    storeName: 'Modern Bazaar, Vasant Vihar',
    location: 'South West Delhi, Delhi',
    gpsCoords: { lat: 28.5605, lng: 77.1611 },
    status: 'NON_COMPLIANT',
    complianceScore: 54,
    createdAt: '2026-09-07T16:20:00Z',
    imageUrl: 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?auto=format&fit=crop&w=800&q=80',
    tamperDetected: false,
    scanSource: 'ecomm_listing',
    declarations: [
      {
        fieldName: 'mrp',
        label: 'Maximum Retail Price',
        value: '₹ 210.00',
        confidence: 96.0,
        status: 'extracted',
        ruleCode: 'LG-MRP',
      },
      {
        fieldName: 'manufacturing_date',
        label: 'Manufacturing Date',
        value: 'MISSING',
        confidence: 95.0,
        status: 'not_found',
        ruleCode: 'LG-DATE',
      },
    ],
    violations: [
      {
        id: 'VIOL-004-1',
        ruleCode: 'LG-DATE',
        ruleTitle: 'Rule 6(1)(d) — Omission of Manufacturing / Packaging Date',
        legalCitation: 'LM(PC) Rules 2011, Rule 6(1)(d)',
        fieldName: 'manufacturing_date',
        severity: 'critical',
        status: 'open',
        message: 'Batch manufacturing month and year declaration missing on physical label.',
        detectedValue: 'Omitted',
        expectedValue: 'MM/YYYY format',
        confidence: 95.0,
        fixSuggestion: 'Add clear MFD / PKG month and year in indelible ink.',
      },
    ],
  },
];

export const SAMPLE_NOTICES: Section36Notice[] = [
  {
    id: 'NOT-2026-0089',
    noticeNumber: 'LM/DEL/CN/2026/0418',
    inspectionId: 'INSP-2026-003',
    productName: 'CrispWave Kettle Cooked Chips 75g',
    brand: 'CrispWave Snacks Ltd',
    companyName: 'CrispWave Agro & Snacks Private Limited',
    companyAddress: 'Industrial Area Phase 2, Panki, Kanpur 208022, Uttar Pradesh',
    gstNumber: '09AAACC4182L1ZT',
    violations: [
      {
        rule: 'LM(PC) Rules 2011 Rule 18(2)',
        section: 'Section 36(1) of Legal Metrology Act 2009',
        description: 'Altering, obliterating or sticking secondary price sticker (₹50) over declared MRP (₹35).',
        severity: 'critical',
      },
      {
        rule: 'LM(PC) Amendment Rules 2021 Rule 6(5)',
        section: 'Section 36(2) of Legal Metrology Act 2009',
        description: 'Complete omission of mandatory consumer grievance contact telephone and email.',
        severity: 'major',
      },
    ],
    draftedAt: '2026-09-09T10:05:00Z',
    status: 'draft',
    issuingOfficer: 'Rajesh Kumar Verma',
    designation: 'District Controller, Legal Metrology Kanpur Zone',
    digitalSignatureHash: 'SHA256:8f4c21980be12c77d901bc0931df332490ecaf541098ef72b',
    penaltyClause: 'Under Section 36 of the Legal Metrology Act, failure to comply attracts compounding fee up to ₹25,000 for first offence, and up to ₹50,000 with imprisonment up to one year for repeat offences.',
    responseDeadlineDays: 15,
  },
  {
    id: 'NOT-2026-0085',
    noticeNumber: 'LM/UP/NOI/2026/0392',
    inspectionId: 'INSP-2026-002',
    productName: 'GlowHerb Ayurvedic Hair Oil 100ml',
    brand: 'GlowHerb Natural Care',
    companyName: 'GlowHerb Ayurvedic Formulations Ltd',
    companyAddress: 'B-12, Sector 4, DSIIDC Bawana, Delhi 110039',
    gstNumber: '07AAACG9912K1Z9',
    violations: [
      {
        rule: 'LM(PC) Rules 2011 Rule 9(6) Table I',
        section: 'Section 36 of Legal Metrology Act 2009',
        description: 'Numeral font height of 0.72mm is lower than statutory requirement of 1.0mm.',
        severity: 'major',
      },
    ],
    draftedAt: '2026-09-08T12:00:00Z',
    status: 'approved',
    issuingOfficer: 'Sunita Sharma',
    designation: 'Assistant Controller of Legal Metrology, Gautam Buddha Nagar',
    digitalSignatureHash: 'SHA256:3a1b9487c992efbc44101ad77309ef3c18bcefa04',
    penaltyClause: 'Compounding notice issued with statutory rectification period of 15 days.',
    responseDeadlineDays: 15,
  },
];

export const SAMPLE_REPEAT_OFFENDERS: RepeatOffender[] = [
  {
    brand: 'CrispWave Snacks Ltd',
    companyName: 'CrispWave Agro & Snacks Private Limited',
    totalScans: 48,
    violationCount: 14,
    criticalCount: 6,
    riskScore: 92,
    topViolationRule: 'Rule 18(2) - Dual MRP / Sticker Overwrite',
    lastViolationDate: '2026-09-09',
    priorityQueueStatus: 'active',
  },
  {
    brand: 'Royal Taste Masala',
    companyName: 'Royal Spices & Condiments LLP',
    totalScans: 35,
    violationCount: 9,
    criticalCount: 4,
    riskScore: 84,
    topViolationRule: 'Rule 5 - Short-Net Quantity Declaration',
    lastViolationDate: '2026-09-07',
    priorityQueueStatus: 'active',
  },
  {
    brand: 'GlowHerb Natural Care',
    companyName: 'GlowHerb Ayurvedic Formulations Ltd',
    totalScans: 29,
    violationCount: 7,
    criticalCount: 1,
    riskScore: 71,
    topViolationRule: 'Rule 9(6) - Sub-Standard Font Height',
    lastViolationDate: '2026-09-08',
    priorityQueueStatus: 'assigned',
  },
  {
    brand: 'Apex Import Trade',
    companyName: 'Apex Continental Goods Pvt Ltd',
    totalScans: 62,
    violationCount: 11,
    criticalCount: 3,
    riskScore: 79,
    topViolationRule: 'Rule 11 - Missing Country of Origin on Imports',
    lastViolationDate: '2026-09-05',
    priorityQueueStatus: 'active',
  },
];

export const SAMPLE_CERTIFICATE: ComplianceCertificate = {
  certificateNumber: 'LM-CERT-2026-88391',
  productName: 'NutriRich Digestive Biscuits (500g)',
  brand: 'NutriRich Foods',
  sku: 'NR-DIG-500G',
  manufacturer: 'NutriRich Foods Pvt Ltd, Greater Noida UP',
  gstin: '09AAACN8841F1ZS',
  complianceScore: 100,
  evaluatedRules: [
    'LM(PC) Rule 4 & 6(1)(a) — Manufacturer Declaration: PASSED',
    'LM(PC) Rule 5 & Sched. II — Net Quantity Metric Standard: PASSED',
    'LM(PC) Rule 6(1)(e) — Maximum Retail Price & USP: PASSED',
    'LM(PC) Rule 6(1)(d) — Manufacturing Date: PASSED',
    'LM(PC) Rule 6(5) — Consumer Grievance Contact: PASSED',
    'LM(PC) Rule 9(6) Table I — Minimum Font Height (≥1.5mm): PASSED',
  ],
  issuedAt: '2026-09-09',
  validUntil: '2027-09-08',
  qrVerificationCode: 'VERIFY-GOV-LM-2026-88391-NRDIG',
  authority: 'Department of Consumer Affairs, Legal Metrology Division, Govt. of India',
  status: 'VALID',
};
